# https://taskfile.dev

version: '3'

tasks:
  up:
    desc: Up mc server
    cmds:
      - docker compose up -d

  down:
    desc: Down mc server
    cmds:
      - docker compose down
  
  logs:
    desc: Show mc server logs
    cmds:
      - docker compose logs -f -t --tail=100
